### ISSUE TITLE
Python Compatibility TODO List

### ISSUE THREAD

**Issue by klange** [klange/kuroko#1]
Kuroko is essentially an incomplete implementation of Python with some quirks. This issue is intended to track what Kuroko is missing or unintentionally does differently.

- [ ] **Tuples**: Are these really any different from lists without mutation? Look into also implementing CPython's freelists for small tuples, which probably requires some GC integration. Syntax support should be fairly straightforward: Detect `TOKEN_COMMA` in a grouping after an expression and switch to tuple processing.
- [ ] **`if` statements in comprehensions**: Implement as an `if` branch that pops and decrements the iterator counter if expression is False?
- [ ] **`print` as a function**: `OP_PRINT` is just a loxism and there's really no reason this couldn't be moved to a native function, including support for the various keyword arguments (`end` is particularly useful). This can happen right now? (Even inclusive of the string coercion...)
- [ ] **`is`**: We only have `==` and there are semantic differences between `is` and `==`. Also `is not`.
- [ ] **Various special methods**: `__get__`/`__set__` should be renamed to their Python counterparts of `__getitem__`/`__setitem__`, we're missing all of the operator ones (`__add__`, `__eq__`, etc.)...
- [ ] **Class fields**: These are just generally useful for defining fixed members or defaults without an init, and also make nicely namespaced enums and whatnot.
- [ ] **Standard Library**: Throwing this very large task in a single checkbox, but there's a lot of ground to cover even just for the basics.
- [ ] **Line feeds in statements**: Inside of parens or brackets, line feeds should be accepted.
